# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui',
# licensing of 'untitled.ui' applies.
#
# Created: Sun Oct 13 03:54:32 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(671, 604)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 231, 191))
        self.frame_2.setStyleSheet("image: url(:/lula/images (1).jpg);\n"
"border-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formFrame = QtWidgets.QFrame(self.frame)
        self.formFrame.setGeometry(QtCore.QRect(240, 10, 421, 181))
        self.formFrame.setAutoFillBackground(False)
        self.formFrame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);")
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setContentsMargins(10, 5, 4, 4)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dateEdit = QtWidgets.QDateEdit(self.formFrame)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_5 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_6 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 200, 231, 121))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 10, 233, 26))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 40, 221, 18))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 60, 233, 14))
        self.checkBox_4.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 80, 233, 14))
        self.checkBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.checkBox.setObjectName("checkBox")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(0, 360, 231, 131))
        self.frame_4.setStyleSheet("image: url(:/digitais-do-lula/images (2).jpg);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(0, 330, 231, 21))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(6, 0, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(240, 200, 421, 31))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formFrame1 = QtWidgets.QFrame(self.frame_6)
        self.formFrame1.setGeometry(QtCore.QRect(0, 0, 421, 41))
        self.formFrame1.setObjectName("formFrame1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formFrame1)
        self.formLayout_2.setContentsMargins(1, 1, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.formFrame1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.formFrame1)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(240, 240, 421, 121))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.formFrame2 = QtWidgets.QFrame(self.frame_7)
        self.formFrame2.setGeometry(QtCore.QRect(9, 9, 401, 111))
        self.formFrame2.setObjectName("formFrame2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formFrame2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.formFrame2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox = QtWidgets.QComboBox(self.formFrame2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_10 = QtWidgets.QLabel(self.formFrame2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formFrame2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_11 = QtWidgets.QLabel(self.formFrame2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formFrame2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formFrame2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_12 = QtWidgets.QLabel(self.formFrame2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(0, 509, 231, 81))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_8)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 221, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(240, 370, 421, 81))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_9)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 0, 411, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_9)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 30, 411, 63))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(240, 460, 421, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_10)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 411, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(250, 550, 411, 41))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_11)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 411, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Nome Completo do Suspeito:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Número completo do CPF", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Número completo do RG:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Data de Nascimento", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Nome Completo da Mãe", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Nome Completo do Pai", None, -1))
        self.frame_3.setWhatsThis(QtWidgets.QApplication.translate("Form", "<html><head/><body><p><img src=\":/lula/images (1).jpg\"/> larão safado</p><p><br/></p><p><br/></p></body></html>", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("Form", "Suspeito matou alguém ?", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("Form", "Precisa devolver Dinheiro ?", None, -1))
        self.checkBox_4.setText(QtWidgets.QApplication.translate("Form", "Ele foi preso Portando alguma arma ?", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("Form", "O Suspeito ser mantém preso ?", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Digitais do suspeito", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Data que o suspeito foi preso", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "Estado que Ocorreu a prisão", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "RJ", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "SP", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "SC", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "MG", None, -1))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "CE", None, -1))
        self.comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "MT", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "Cidade que Ocorreu a prisão", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "Bairro, Condomínio ou SÍTIO", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "Nome Da Rua ou o CEP", None, -1))
        self.checkBox_5.setText(QtWidgets.QApplication.translate("Form", "Foi necessário o uso da Força ?", None, -1))
        self.checkBox_6.setText(QtWidgets.QApplication.translate("Form", "O exame de Corpo delito foi feito ?", None, -1))
        self.checkBox_7.setText(QtWidgets.QApplication.translate("Form", "Veículos Apreendido ?", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Form", "Crimes cometidos", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("Form", "157", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("Form", "133", None, -1))
        self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("Form", "149", None, -1))
        self.comboBox_2.setItemText(3, QtWidgets.QApplication.translate("Form", "333", None, -1))
        self.comboBox_2.setItemText(4, QtWidgets.QApplication.translate("Form", "155", None, -1))
        self.comboBox_2.setItemText(5, QtWidgets.QApplication.translate("Form", "166", None, -1))
        self.comboBox_2.setItemText(6, QtWidgets.QApplication.translate("Form", "168", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "Adicionar Crime", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Form", "Limpar Crime", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("Form", "Mostra Crimes do suspeito", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("Form", "Cadastrar Condenado!", None, -1))

#from suspeito_rc import * 
#from digitais_rc import *

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

